version: 0.2
phases:
  build:
    commands:
      - echo $ECS_CLUSTER_NAME
      - echo $ECS_SERVICE_NAME
      - echo $REPO
      - ECR_IMAGES=$(aws ecr describe-images --repository-name $REPO --query 'imageDetails' --output text)
      - echo $ECR_IMAGES
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
        